import turtle

lander=turtle.Turtle()
lander.color('black','grey')
lander.begin_fill()
lander.forward(100)
lander.left(90)
lander.left(45)
lander.forward(35)
lander.left(45)
lander.forward(50)
lander.left(45)
lander.forward(35)
lander.end_fill()
lander.left(45)
lander.color('black','yellow')
lander.begin_fill()
lander.forward(50)
lander.left(45)
lander.forward(25)
lander.left(45)
lander.forward(65)
lander.left(45)
lander.forward(25)
lander.left(45)
lander.forward(50)
lander.end_fill()
lander.left(45)
lander.forward(35)
lander.right(90)
lander.color('grey','blue')
lander.begin_fill()
lander.left(90)
lander.circle(35,100)
lander.left(125)
lander.forward(60)
lander.end_fill()
lander.color('black','orange')
lander.begin_fill()
lander.forward(100)
lander.right(130)
lander.forward(200)
lander.right(50)
lander.forward(20)
lander.right(50)
lander.forward(200)
lander.right(130)
lander.forward(120)
lander.up()
lander.right(83)
lander.forward(150)
lander.down()
lander.end_fill()




turtle.mainloop()
